### ISSUE TITLE
How can we override the currently used icons

### ISSUE THREAD

**Issue by nickbe** [somewebmedia/hc-offcanvas-nav#32]
How can we change the arrow up/down as well as the close icons?

**Comment by somewebmedia** [comment]
You would have to override them with css.

**Comment by nickbe** [comment]
Can you tell me how or rather where? For the love of it I don't get how the current icons are created at all.

**Comment by somewebmedia** [comment]
Here is how the structure looks like:

```css
.hc-offcanvas-nav .nav-close span {}
.hc-offcanvas-nav .nav-close span::before {}
.hc-offcanvas-nav .nav-close span::after {}

.hc-offcanvas-nav .nav-next span {}
.hc-offcanvas-nav .nav-next span::before {}

.hc-offcanvas-nav .nav-back span {}
.hc-offcanvas-nav .nav-back span::before {}
```
So you should put icons on those `::before` pseudo elements, and hide `::after`with `display:none;` on close button.

**Comment by nickbe** [comment]
Thanks - I'll try this.

**Comment by cabintech** [comment]
Is this answer still correct? I think the CSS may have changed since 2020. I am trying to do this now. I want to change the "X" close button to "<<" as that better represents the behavior. I can do this:

.hc-offcanvas-nav .nav-close span::before {
	content: '<<' !important;
}

and I get the << partially rotated, and the "X" still shows up (like the original poster, I don't see where the "X" shape even comes from). Can you provide an example of what is needed to make this work?

**Comment by somewebmedia** [comment]
That is ok, you just have to remove the border and set the proper line height.

```
.hc-offcanvas-nav .nav-close span::before {
    transform: rotate(0deg) !important;
    content: '<<' !important;
    border: none !important;
    line-height: 1;
}

.hc-offcanvas-nav .nav-close span::after {
    display:none !important;
}
```
